[package]
name = "rustmcserver"
version = "0.1.0"
authors = ["StackDoubleFlow <ojaslandge@gmail.com>"]
edition = "2018"

[dependencies]
openssl = "0.10.24"
flate2 = "1.0"
base64 = "0.10.1"
serde_json = "1.0.40"
rand = "0.7.0"

[profile.dev]
opt-level = 0